### ISSUE TITLE
404 - file not found for file: css/images/layers.png

### ISSUE THREAD

**Issue by jveldhuizen** [mendix/Leaflet#11]
If you choose 'Show categories', the layer image is not shown and you get the following error:

404 - file not found for file: css/images/layers.png  
or  
404 - file not found for file: css/images/layers-2x.png

**Comment by JelteMX** [comment]
Can you update to the latest version? I haven't encountered this issue and it shouldn't happen. The images are added to the widget, but in the CSS they are base64 strings, not a reference to a file.
