### ISSUE TITLE
Feature: geocoding search

### ISSUE THREAD

**Issue by JelteMX** [mendix/Leaflet#4]
Let the use have the possibility to look for an address, by using one of the [geocoding plugins](http://leafletjs.com/plugins.html#geocoding)

**Comment by pimvdnoll** [comment]
Definitely a good addition, I have a use case atm for searching for an address and place a marker. 
Is it hard to implement a plugin?

**Comment by JelteMX** [comment]
I already did a quick test with [leaflet-geosearch](https://github.com/smeijer/leaflet-geosearch). The problem with that one is that it doesn't expose it properly, as it is written in ES6 and build with webpack. Should be a great feature, but first I need to properly get this library working

**Comment by pimvdnoll** [comment]
I got this working: https://github.com/perliedman/leaflet-control-geocoder but I could not get to the mendix specific functions to execute microflow etc..
see attachment
[Leaflet_8309b0f7fd97e8dbb217bf76f56993965ad7252c.zip](https://github.com/mendix/Leaflet/files/684505/Leaflet_8309b0f7fd97e8dbb217bf76f56993965ad7252c.zip)

**Comment by JelteMX** [comment]
Does this work in the cloud as well? I doubt it because of the structure of Geocoder

**Comment by pimvdnoll** [comment]
don't know, only tested locally..

**Comment by JelteMX** [comment]
Finally added to [v2.2.0](https://github.com/mendix/Leaflet/releases/tag/v2.2.0)
