### ISSUE TITLE
Update to Leaflet 1.0

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/Leaflet#8]
Final  is out: http://leafletjs.com/2016/09/27/leaflet-1.0-final.html

**Comment by JelteMX** [comment]
Awesome, will test & update this week

**Comment by pimvdnoll** [comment]
Cool!

**Comment by JelteMX** [comment]
Updated in [1.2.0](https://github.com/mendix/Leaflet/releases/tag/v1.2.0)

**Comment by pimvdnoll** [comment]
top!
